#!/bin/bash

# List of packages to install on OpenWRT
OPENWRT_PACKAGES="iptables-mod-ipopt nftables iptables-zz-legacy ip6tables-zz-legacy"

# List of packages to install on generic Linux (Debian-based)
GENERIC_LINUX_PACKAGES="iptables nftables"

# Function to detect OpenWRT
is_openwrt() {
    [ -f /etc/openwrt_release ]
}

# Function to detect Debian-based Linux
is_debian() {
    [ -f /etc/debian_version ]
}

# Function to install packages on OpenWRT
install_openwrt_packages() {
    echo "Installing Dependencies on OpenWRT: $OPENWRT_PACKAGES"
    opkg install $OPENWRT_PACKAGES
}

# Function to install packages on Debian-based Linux
install_generic_linux_packages() {
    echo "Installing Dependencies on Linux: $GENERIC_LINUX_PACKAGES"
    sudo apt install -y $GENERIC_LINUX_PACKAGES
}

# Main logic
if is_openwrt; then
    echo "OpenWRT detected."
    install_openwrt_packages
elif is_debian; then
    echo "Debian-based Linux detected."
    install_generic_linux_packages
else
    echo "Unsupported OS. This script is intended for OpenWRT or Debian-based Linux."
    exit 1
fi

# Ipv4 and Ipv6 Forwarding
cat >> /etc/sysctl.conf << EOF
net.ipv6.conf.all.forwarding=1
net.ipv4.ip_forward=1
EOF
###
sysctl -p
###
echo "Installing iptables rule in /etc/iptables/rules.v4..."
###
cat > /etc/iptables/rules.v4 << EOF
# Append the incoming ipv4 TTL hop limit from 1 and increase to 64 before routing.
iptables -t mangle -A PREROUTING -j TTL --ttl-set 64

# Append the incoming ipv6 HL hop limit from 1 and increase to 64 before routing.
ip6tables -t mangle -A PREROUTING -j HL --hl-set 64
EOF
###
chmod +x /etc/iptables/rules.v4
###
sh /etc/iptables/rules.v4
###
echo 'Done'
###
iptables -vnL --line-numbers
###
ip6tables -vnL --line-numbers
