#!/bin/bash

# Ipv4 and Ipv6 Forwarding
cat >>/etc/sysctl.conf << EOF
net.ipv6.conf.all.forwarding=1
net.ipv4.ip_forward=1
EOF
###
sysctl -p
###
echo "adding nftables to /etc/nftables.d/ttl64.nft"
###
cat >>/etc/nftables.d/ttl64.nft << EOF
chain mangle_prerouting_ttl64 {
                type filter hook prerouting priority 300; policy accept;
                ip ttl set 64
                ip6 hoplimit set 64
        }

chain mangle_postrouting_ttl64 {
                type filter hook postrouting priority 300; policy accept;
                ip ttl set 64
                ip6 hoplimit set 64
        }
EOF
###
fw4 check
/etc/init.d/firewall restart
###
echo "Done installing config to /etc/nftables.d/"
echo "nftable is running now with a ttl=64"
nftables list ruleset
