#!/bin/bash

# List of packages to install on OpenWRT
OPENWRT_PACKAGES="nftables kmod-nft-nat kmod-nft-core kmod-nfnetlink"
# List of packages to install on generic Linux (Debian-based)
GENERIC_LINUX_PACKAGES="nftables"

# Function to detect OpenWRT
is_openwrt() {
    [ -f /etc/openwrt_release ]
}

# Function to detect Debian-based Linux
is_debian() {
    [ -f /etc/debian_version ]
}

# Function to install packages on OpenWRT
install_openwrt_packages() {
    echo "Installing Dependencies on OpenWRT: $OPENWRT_PACKAGES"
    opkg install $OPENWRT_PACKAGES
}

# Function to install packages on Debian-based Linux
install_generic_linux_packages() {
    echo "Installing Dependencies on Linux: $GENERIC_LINUX_PACKAGES"
    sudo apt install -y $GENERIC_LINUX_PACKAGES
}

# Main logic
if is_openwrt; then
    echo "OpenWRT detected."
    install_openwrt_packages
elif is_debian; then
    echo "Debian-based Linux detected."
    install_generic_linux_packages
else
    echo "Unsupported OS. This script is intended for OpenWRT or Debian-based Linux."
    exit 1
fi

# Ipv4 and Ipv6 Forwarding
cat >>/etc/sysctl.conf << EOF
net.ipv6.conf.all.forwarding=1
net.ipv4.ip_forward=1
EOF
###
sysctl -p
###
echo "adding nftables to /etc/nftables.d/ttl64.nft"
###
cat >>/etc/nftables.d/ttl64.nft << EOF
chain mangle_prerouting_ttl64 {
                type filter hook prerouting priority 300; policy accept;
                ip ttl set 64
                ip6 hoplimit set 64
        }

chain mangle_postrouting_ttl64 {
                type filter hook postrouting priority 300; policy accept;
                ip ttl set 64
                ip6 hoplimit set 64
        }
EOF
###
fw4 check
/etc/init.d/firewall restart
###
echo "Done installing config to /etc/nftables.d/"
echo "nftable is running now on wlan0 to eth0 with a ttl=64"
nftables list ruleset
